### ISSUE TITLE
Minimizing collapses Ace window

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace-gui#58] opened 2019-07-20 01:33 UTC
Windows 10 Pro x64 1903
Ace GUI - Version: 1.0.0-beta.2

Steps to reproduce issue:

- Open the GUI;
- Click on the minus (-) button to minimize, or click on the app icon on the task bar;
- Click on the app icon to restore the window;
- Now the window is really small, showing just Ace logo, 'maximize', and 'close' buttons;
- If I adjust the window size, the error no longer occur until restarting the app.

**Comment by danielweck** [comment] 2019-12-05 11:18
I am unable to reproduce this bug. Closing the issue, but please feel free to re-open if the bug persists.

**Closed by danielweck** 2019-12-05 11:18 UTC
