### ISSUE TITLE
Reduce the load time

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-gui#9] opened 2018-10-11 13:14 UTC
Currently Ace takes a few seconds to load, which isn't an ideal user experience.

We should:
- try to reduce the loading time. Bundling the renderer-level javascript (with webpack) could improve the situation
- see if we can display a loader and message while React loads asynchronously

**Comment by danielweck** [comment] 2019-12-05 11:30
I am closing this issue as I am unable to reproduce this kind of UI latency. Perhaps at the time when this issue was filed, the build system was suboptimal, but the WebPack bundling now results in acceptable load-time / runtime launch performance.

**Closed by danielweck** 2019-12-05 11:30 UTC
