### ISSUE TITLE
Concurrent Winston log access when command line tool and GUI app are used in parallel

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace-gui#50] opened 2019-05-12 09:58 UTC
This is a minor issue. Maybe its by design: when I check a book with the GUI and then try to run the command line tool while the GUI is still open, then I get this error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, stat 'C:\Users\go_th\AppData\Local\DAISY Ace\Log\ace.log'
Emitted 'error' event at:
    at C:\Users\go_th\AppData\Roaming\npm\node_modules\@daisy\ace\node_modules\winston\lib\winston\transports\file.js:542:23
    at FSReqCallback.oncomplete (fs.js:160:21)
```

Looks like the GUI is keeping the log file open even after it finished the check.

**Comment by danielweck** [comment] 2019-05-13 08:40
Good catch! Let's try to fix this.
MacOS uses different temp/user folders, but the problem is probably exactly the same as on Windows (as reported here).

Possible solution: configure different paths for standalone Ace core CLI vs. Ace-GUI programmatically-driven Ace core commands.

**Comment by danielweck** [comment] 2019-08-10 16:43
Yes, the Winston logger is "alive" for the duration of the app (not just the duration of a single Ace check).
Related issue: https://github.com/daisy/ace/issues/68#issuecomment-520163210

**Comment by danielweck** [comment] 2019-08-10 17:20
Fixed via https://github.com/daisy/ace-gui/commit/5218f542ecf1144be1629564030a8eca258ca739

**Closed** 2019-08-10 17:20 UTC
