### ISSUE TITLE
Aucune image dans cette publication

### ISSUE THREAD

**Issue by laudrain** [daisy/ace-gui#76] opened 2019-08-05 07:27 UTC
with Ace by DAISY 1.0.0-rc.1
No image detected in an EPUB with 2 images
From report.json issue by Ace 1.1.1:
`  "data": {
    "images": [
      {
        "src": "OPS/cover/cover.jpg",
        "alt": "Couverture : Dubois Christophe, Tabet Marie-Christine, Descente aux enfers (Vie et mort de la SNCF), Fayard",
        "role": "doc-cover",
        "html": "<img xmlns=\"http://www.w3.org/1999/xhtml\" src=\"cover/cover.jpg\" alt=\"Couverture : Dubois Christophe, Tabet Marie-Christine, Descente aux enfers (Vie et mort de la SNCF), Fayard\" class=\"imgpp\" role=\"doc-cover\" />",
        "location": "cover.xhtml#epubcfi(/4/2/2[cover]/2)"
      },
      {
        "src": "OPS/cover/pagetitre.jpg",
        "alt": "Page de titre : Dubois Christophe, Tabet Marie-Christine, Descente aux enfers (Vie et mort de la SNCF), Fayard",
        "role": null,
        "html": "<img xmlns=\"http://www.w3.org/1999/xhtml\" src=\"cover/pagetitre.jpg\" alt=\"Page de titre : Dubois Christophe, Tabet Marie-Christine, Descente aux enfers (Vie et mort de la SNCF), Fayard\" class=\"imgpp\" />",
        "location": "pagetitre.xhtml#epubcfi(/4/2/2[pagetitre]/2)"
      }
    ]
  },
`

**Comment by danielweck** [comment] 2019-08-05 14:03
Hello Luc, are you able/allowed to share the EPUB publication so we can try to reproduce the bug at our end?

**Comment by danielweck** [comment] 2019-08-05 14:04
Seems related to issue https://github.com/daisy/ace/issues/263 (now solved, but not yet published in official Ace App release)

**Comment by danielweck** [comment] 2019-08-05 14:05
Possibly related issue: https://github.com/daisy/ace-gui/issues/77

**Comment by laudrain** [comment] 2019-08-05 14:38
@danielweck just checked again before sending the EPUB, but could not reproduce it.
Nor with other EPUB files...
Let's close the issue for the moment.

**Comment by danielweck** [comment] 2019-08-10 14:35
I believe this "random" bug is now fixed, via these code changes in Ace ("random" because very sensitive to execution timing, due to an HTML-loading bug in Electron):
https://github.com/daisy/ace/commit/368f8c3d98f87de9ac5b58e876bc742c2c6b62c7
https://github.com/daisy/ace/commit/dc71e4c517523c5477b6ea52af02157987fa7bbf

Note that this code is from the Electron-based Axe runner implementation available in this Pull Request (which is specifically maintained for the Ace App, not yet merged into the Ace `master` branch):
https://github.com/daisy/ace/pull/236

**Closed by danielweck** 2019-08-10 14:35 UTC
