### ISSUE TITLE
Requesting the ability to run on expanded EPUB folders

### ISSUE THREAD

**Issue by CircularKen** [daisy/ace-gui#67] opened 2019-08-01 14:45 UTC
I would like ACE GUI to be modified so I can interrogate an open folder rather than a ZIPped EPUB.

Currently, I’m having to continually compress to check and uncompress to then fix and then compress again to check once more!

For example the neat pagina EPUB-checker validation GUI that I use has this simple and useful feature and it speeds up EPUB development considerably.

Thanks everyone, keep up the good work!

**Comment by danielweck** [comment] 2019-08-01 16:18
Related issue: https://github.com/daisy/ace/issues/255

**Comment by marisademeglio** [comment] 2019-08-01 20:07
I tried to reproduce using an installed version of v1.0.0-RC1 on macOS and I find that when I drag a folder onto the sidebar, it runs, but when I choose from the menu, it doesn't work. 

E.g. from drag+drop:
```
Running Ace on /Users/marisa/dev/epub3-samples/30/childrens-literature
Ace check complete
Loaded report /var/folders/5x/ygb2lg651kg115pdk0hbh9q40000gn/T/tmp-22220H6r1KmX67BMS/childrens-literature/report.json
```

vs from menu: 
```
Running Ace on /Users/marisa/dev/epub3-samples/30/cc-shared-culture
[object Object]
```

**Comment by danielweck** [comment] 2019-08-01 20:17
I am able to check exploded EPUBs (folders) by:
* drag-drop into central window area
* drag-drop into "Check EPUB" left-hand-side menu item
* "click to browse" link in central window area
* "Check EPUB" menu item

However, just like Marisa's experience, the "Check EPUB" top-level system menu fails.

**Comment by danielweck** [comment] 2019-08-01 20:18
Ah, the top-level system menu "Check EPUB" always fail (packed and exploded EPUBs)

**Comment by danielweck** [comment] 2019-08-01 20:21
I am closing this issue, as support for unzipped EPUBs seems to be working just fine. Free free to re-open if needed. Thank you very much for your feedback! :)

**Closed by danielweck** 2019-08-01 20:21 UTC
